USE [master]
GO

/****** Object:  Database [NameGenerator]    Script Date: 1/22/2016 1:46:37 AM ******/
CREATE DATABASE [NameGenerator]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NameGenerator', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\NameGenerator.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NameGenerator_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\NameGenerator_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NameGenerator] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NameGenerator].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NameGenerator] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NameGenerator] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NameGenerator] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NameGenerator] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NameGenerator] SET ARITHABORT OFF 
GO

ALTER DATABASE [NameGenerator] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NameGenerator] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NameGenerator] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NameGenerator] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NameGenerator] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NameGenerator] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NameGenerator] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NameGenerator] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NameGenerator] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NameGenerator] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NameGenerator] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NameGenerator] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NameGenerator] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NameGenerator] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NameGenerator] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NameGenerator] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NameGenerator] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NameGenerator] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NameGenerator] SET  MULTI_USER 
GO

ALTER DATABASE [NameGenerator] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NameGenerator] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NameGenerator] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NameGenerator] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NameGenerator] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NameGenerator] SET  READ_WRITE 
GO


