//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyNameGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class full_name
    {
        public int FirstID { get; set; }
        public int MiddleID { get; set; }
        public bool Good { get; set; }
        public int ID { get; set; }
    
        public virtual first_name first_name { get; set; }
        public virtual middle_name middle_name { get; set; }
    }
}
